### PR TITLE
4 ➡️ 5 (main)

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `ign-common4` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-common/compare/main...ign-common4

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by mjcarroll** [comment]
Looks like this is conflicted/failing CI.

**Comment by chapulina** [comment]
Now pending `libignition-math7-dev` as part of 

* https://github.com/ignition-tooling/release-tools/issues/566

**Comment by chapulina** [comment]
humm still having some Jammy CI issues

```
  The following packages have unmet dependencies:
   ruby-kramdown : Depends: ruby-rexml but it is not installable
                   Recommends: ruby-rouge but it is not going to be installed
```

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
