### PR TITLE
Add cstring for `std::memcpy`

### PR DESCRIPTION
**Pull request by kunaltyagi**
## Summary

Just a simple fix for a really weird compilation error. Shouldn't have seen it, but saw it, so created a tiny PR

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by mjcarroll** [comment]
Thanks for the contribution!  Can you signoff your commit so that DCO will pass?

**Review by mjcarroll — APPROVED** [review]
LGTM, awaiting DCO signoff.

**Comment by mjcarroll** [comment]
@kunaltyagi friendly ping on DCO signoff.

**Comment by kunaltyagi** [comment]
Sorry for the delay, was on a holiday

**Pull request merged**
