### PR TITLE
Fix a typo in VideoEncoder_TEST.

### PR DESCRIPTION
**Pull request by mahiuchun**
The same typo is also in `ign-common4` and `main` branches.

### CODE REVIEW

**Comment by mahiuchun** [comment]
Looks like `mpg` rather than `mp4` passes in the CI, is this the right behavior though?

**Comment by scpeters** [comment]
> Looks like `mpg` rather than `mp4` passes in the CI, is this the right behavior though?

I see why you made this change, but it causes the test to fail. I don't understand the code well enough to say why

**Comment by mjcarroll** [comment]
> I see why you made this change, but it causes the test to fail. I don't understand the code well enough to say why

I agree that the change is correct, but the failure is very strange.

**Comment by mjcarroll** [comment]
The issue here was that the test was calling `Start` twice without a `Stop` or `Reset` in between the two `Start` calls.  I have added some more comprehensive tests to test default, `mpg`, and `mp4` encoding, as well as testing the multiple `Start` case.

**Review by chapulina — APPROVED** [review]

**Pull request merged**
