### PR TITLE
🎈 3.11.0

### PR DESCRIPTION
**Pull request by chapulina**
# 🎈 Release

Preparation for 3.11.0 release.

Comparison to 3.10.1: https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.10.1...ign-common3

Needed by:
* https://github.com/ignitionrobotics/ign-gui/pull/170
* https://github.com/ignitionrobotics/ign-physics/pull/202

## Checklist
- [x] Asked team if this is a good time for a release (CC @mjcarroll )
- [x] There are no changes to be ported from the previous major version
- [x] No PRs targeted at this major version are close to getting in
- [x] Bumped minor for new features, patch for bug fixes
- [x] Updated changelog
- [ ] ~~Updated migration guide (as needed)~~
- [ ] ~~Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>~~

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by peci1** [comment]
Oh no, @chapulina, you broke our detectors!

3.10.1:

Snímek z 2021-03-09 00-53-04

3.11.0:

Snímek z 2021-03-09 00-53-57

As mentioned in https://github.com/ignitionrobotics/ign-common/pull/151#issuecomment-783795446 , #151 should be reverted and it should come with a better solution.

**Comment by peci1** [comment]
And the links for 3.11.0 PRs in changelog are wrong (they refer to `.../pulls/151` while it should be `.../pull/151`).

**Comment by chapulina** [comment]
Reverting #151: https://github.com/ignitionrobotics/ign-common/pull/182

**Comment by chapulina** [comment]
This release is also broken on arm64 and armhf because of #125: #180

**Pull request merged**
