### PR TITLE
Avoid duplication of / in joinPaths (Windows)

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

Fixes #<NUMBER>

Related with this issue https://github.com/ignitionrobotics/ign-fuel-tools/pull/178

## Summary
When we use `JoinPaths` with a empty string we can have some extra ' /' which generates some issues on Windows. As a explained [here](https://github.com/ignitionrobotics/ign-fuel-tools/pull/178#discussion_r612633922). This PR remove the '/' at the beginning and end of the string.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
Can we add some test cases that demonstrate the fix? Also, should we make the behavior consistent across platforms?

**Comment by ahcorde** [comment]
> Also, should we make the behavior consistent across platforms?

I can remove the `/` at the end of the string, but at the beginning of the string in an Unix like system is a bad idea because I can modify an absolute path

**Comment by ahcorde** [comment]
MacOS warnings are unrelated

**Comment by chapulina** [comment]
I pushed a test in 6c4f5d6, LGTM if it passes.

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
MacOS warnings are unrelated

**Pull request merged**
